name: Scrape latest data

on:
  push: 
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron:  '39 20 * * 1-5'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Search shared pages
      run: |-
        sh ./scripts/query_pages.sh
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    - name: Query til db
      run: |-
        sh ./scripts/query_til_db.sh | jq '.results[] | {id: .id, title: .properties.Name.title[0].text.content, tags: [.properties.Tags.multi_select[].name] }'
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        TIL_DATABASE_ID: ${{ secrets.TIL_DATABASE_ID }}
